### ISSUE TITLE
Module load not error.

### ISSUE THREAD

**Issue by quazirafi** [jordiae/exebench#2]
I did everything like this but got this error. Can you tell what went wrong?

git clone https://github.com/jordiae/exebench.git
cd exebench/
python -m venv venv
source venv/bin/activate
pip install -r requirements_examples.txt
python3 examples/basic.py

Error Message
---------------
---------------
Traceback (most recent call last):
  File "examples/basic.py", line 2, in <module>
    from exebench import Wrapper, diff_io, exebench_dict_to_dict
ModuleNotFoundError: No module named 'exebench'

**Comment by jordiae** [comment]
Hey, thanks for your interest and apologies for the late reply! This seems to be happening because the ExeBench module is not included in your path. Could you try `PYTHONPATH="${PYTHONPATH}:${pwd}" python examples/basic.py` ?

**Comment by jordiae** [comment]
Any updates? @quazirafi
