### ISSUE TITLE
Majority of data seems to be missing synth_exe_wrapper or real_exe_wrapper

### ISSUE THREAD

**Issue by henrycharlesworth** [jordiae/exebench#3]
Hi,

I have downloaded through Hugging Face, but I am finding when I iterate over the splits "train_synth_compilable" and "train_real_compilable" that most of the entries do not have one of "synth_exe_wrapper" or "real_exe_wrapper". Is this an error? How can I compile them without this wrapper? Because as far as I can tell the example code requires this to be present in order to compile them.

**Comment by jordiae** [comment]
Hi Henry. This is expected. The wrappers are not needed for compilation, but for execution. Thus, the wrappers are present in the executable subsets (the ones with I/O examples, corresponding to the splits with "io" in their name), but not (or not necessarily) in the compilable ones.

Are you interested in "just" compiling or also in executing? For compiling, you just need, e.g. for  `train_synth_compilable`:  `row['synth_deps'] + '\n' + row['func_def']`. 

Does this help? Let me know if it works or need anything else.

**Comment by henrycharlesworth** [comment]
Yes, I figured this out after playing around a bit more, apologies :). I'm only interested in compiling at the moment.

But actually I've found that doing this:

```
c_code = ""
if row["synth_deps"] is not None:
    c_code += row["synth_deps"]
if row["real_deps"] is not None:
    c_code += "\n" + row["real_deps"]
c_code += "\n" + row["func_def"]
```

only successfully compiles for about 87% of the functions in the dataset (of those that should be compilable). Any ideas what might be causing this?

**Comment by jordiae** [comment]
> Yes, I figured this out after playing around a bit more, apologies :). I'm only interested in compiling at the moment.
> 
> But actually I've found that doing this:
> 
> ```
> c_code = ""
> if row["synth_deps"] is not None:
>     c_code += row["synth_deps"]
> if row["real_deps"] is not None:
>     c_code += "\n" + row["real_deps"]
> c_code += "\n" + row["func_def"]
> ```
> 
> only successfully compiles for about 87% of the functions in the dataset (of those that should be compilable). Any ideas what might be causing this?

Great! No need to apologize, I should have clarified this in the example.

The first thing I would note is that your second `if` should be an `elif`, just in case a function has both of them (which would cause a conflict). Other than that, it might be either a discrepancy between the compilation flags and/or libraries in your host system and the machines I used to compile them. How are you compiling exactly?

**Comment by henrycharlesworth** [comment]
Thanks for the response! So we should never be combining the real and synthetic dependencies? but they do sometimes have both - in which case which one should I choose? I guess based on whether the dataset split is real or synth?

I have been using `gcc -O0 -o fcn_out -c fcn.c -I path_to_synth_deps` - does this seem right?

As an aside - my actual use case is that I want to compile the functions with different optimizations. But I am finding at the moment when I use anything higher than O0, that when I inspect the output with `objdump -d fcn_out` that the function is missing (I guess it's being treated as dead code?) I've tried a few things to get around this but haven't been able to get it working yet. Did you come across this issue at all/ have any suggestions for how to do this in a better way?

**Comment by jordiae** [comment]
No, we should never combine them. If they have both, it's a matter of your preference. But yes, the functions in the `synth` splits always have `synth_deps`, and the `real` ones always have `real_deps`. 

The command you are using does seem right.

I have encountered the issue you mention in some cases. I typically use the -S target to get the assembly, and more frequently than not I do get what I was looking for.  FYI, the dataset has a branch with lots of optimization targets already pre-compiled (although they are preprocessed to be just the functions themselves, so it might or might not work for your use case). If you want to give it a try (it also has a streaming mode that can help you avoid downloading the whole dataset at once), proceed as follows:

```
split = 'train_synth_compilable'
dataset = load_dataset('jordiae/exebench', split=split, revision='clang', subsets=[split], streaming=True)
for row in dataset:
    target = 'angha_gcc_x86_O0' # angha_gcc_x86_O3, angha_clang_arm_O3, etc. If it's a "real" split, then replace the "angha" prefix with "real"
    func_assembly = row['asm']['code'][row['asm']['target'].index(target)]

```

If I try this with the first function in the split, `sacaC`, I compile the resulting assembly with GCC, and then I use `objdump`, I do find the function there. Hope this helps.

**Comment by henrycharlesworth** [comment]
Thanks.

I will investigate if it's happening all the time or just occasionally. 

I did see there were some precompiled stuff. I don't think that's quite what I want though - we have a sequencer that does a bunch of stuff so the output won't be normal assembly code. So I just want to compile the functions with various optimizations and then analyse them all with our sequencer

**Comment by jordiae** [comment]
I see! Let me know if it ends up working for you. Closing the issue for now, but thanks for reaching out, and feel free to contact me again.

**Comment by jordiae** [comment]
@henrycharlesworth Out of curiosity, do you get the same behavior with clang?

**Comment by henrycharlesworth** [comment]
Just tried a couple of examples and yes, still seeing the same thing (actually seems like it might be even worse)

**Comment by jordiae** [comment]
> Just tried a couple of examples and yes, still seeing the same thing (actually seems like it might be even worse)

Interesting, will take a look.
